export const DATABASE_ID = process.env.NEXT_PUBLIC_APPWRITE_DATABASE_ID!;
export const IMAGES_BUCKET_ID = process.env.NEXT_PUBLIC_APPWRITE_IMAGES_BUCKET_ID!;

export const REPORTS_ID = process.env.NEXT_PUBLIC_APPWRITE_REPORTS_ID!;
export const ACHIEVEMENTS_ID = process.env.NEXT_PUBLIC_APPWRITE_ACHIEVEMENTS_ID!;
export const ATTENDANCE_ID = process.env.NEXT_PUBLIC_APPWRITE_ATTENDANCE_ID!;
export const GROUPS_ID = process.env.NEXT_PUBLIC_APPWRITE_GROUPS_ID!;
export const TEACHERS_ID = process.env.NEXT_PUBLIC_APPWRITE_TEACHERS_ID!;
export const STUDENTS_ID = process.env.NEXT_PUBLIC_APPWRITE_STUDENTS_ID!;
